### PR TITLE
Angular 9 migrate

### PR DESCRIPTION
**Pull request by jecraig**
Resolves https://github.com/KingSora/OverlayScrollbars/issues/210

Made the library an angular library so it's easier to update in the future just using ng update.

You should be able to just publish the /dist folder and everything will work. I tested it locally on my project and it all went as expected.

### CODE REVIEW

**Comment by KingSora** [comment]
Good day!

Thank you very mich for your contribution! Could you explain to me what you did differently from my project setup / why yours is more correct than the previous one? I'm just a bit confused because the fix for #210 would be just a small change in the `package.json` and the project already has a angular version.

**Comment by jecraig** [comment]
This is the default way that the Angular team has setup for building libraries. The advantages of it are that you can use the angular migrations for any future updates. You also don't have to fiddle around with how to package the library for angular consumption. Essentially, it will make it easier for angular devs to submit PRs in the future.

**Comment by KingSora** [comment]
I'm tending to keep the current implementation because currently there are many duplicated files such as `package.json`, `README.md`, `tslint.json`, `tsconfig.json` and so on which I don't really like. That was also part of the reason I choosed not to use `ng-packagr` because of the huge boilerplate. 

Please don't take this as a personal attack, I'm really thankful for your contribution!

**Comment by jecraig** [comment]
No offence taken.

**Pull request closed without merging**
