### PR TITLE
Rewrite react component with hooks

### PR DESCRIPTION
**Pull request by tooppaaa**
No changes, no new features. Just remove classes.

Context:

Had some issue with IE11 regarding the esm module to be used and not going through babel for unknown reasons.

### CODE REVIEW

**Comment by KingSora** [comment]
Good day,
thank you very much for your contribution!

I have one problem which needs to be solved. As mentioned in the documentation [here](https://github.com/KingSora/OverlayScrollbars/tree/master/packages/overlayscrollbars-react#instance) you should be able to get the `ref` of the component and the `ref` should have two methods called `osInstance()` and `osTarget()`. As far as I see this isn't the case anymore.

Do you have a idea how to solve this problem?

**Comment by ndelangen** [comment]
@KingSora What's the purpose of those instance methods? and could they potentially be changed into hooks / a hook?

**Comment by tooppaaa** [comment]
Missed this ! sorry ! 

I guess we can use 
```
React.useImperativeHandle(ref, () => ({
    osInstance: () => osInstance.current,
   osTarget: () => osTarget.current,
  }));
```

What do you think ?

**Comment by KingSora** [comment]
@ndelangen Basically they are just there so that you can access the `OverlayScrollbars instance` and the `target element` more easy.

@tooppaaa I'm not so familiar with the `useImperativeHandle` hook, but it looks fine to me. Could you check the example app in the `example` folder before and after your change? Check the console output after your clicked on the `log` button and compare it. If both versions provide the same information, the problem is solved.

**Comment by tooppaaa** [comment]
It looks like it's working for me, you know better can you double check ?
image


I think I also break formatting on save.

Downside: **This is a breaking change**. The usage you did in App with classes doesn't work with functions...
I let you review !

**Comment by KingSora** [comment]
@tooppaaa this looks good to me!

What do you mean with breaking change?.. Could you go into details about what you mean? Is it because of the new interface for the Handle in TypeScript?

**Comment by tooppaaa** [comment]
Part of this yes.

`RefObject<OverlayScrollbarsComponent>;` Will cause an error in typescript.
It's not a breaking change in terms of implementation.

**Comment by KingSora** [comment]
Alright, Thanks!
I'm really unsure how to handle this change in terms of versioning, since only TypeScript users will be affected because of a new implementation. Does someone have a recommendation?

**Comment by ndelangen** [comment]
When in doubt, do a major version bump?

**Comment by KingSora** [comment]
I'm very satisfied with this PR, I'll definitely merge it when the time for the next major version for the wrapper components. Thank you once again!!

**Comment by ndelangen** [comment]
What's the time-table on that major version release?

We've got the code copied into our codebase now, and have removed the dependency.

This means if me or @tooppaaa forget, we'll never receive the update.

Could you ping us?

**Comment by KingSora** [comment]
@ndelangen I'll mention you both in this PR before I merge it, so you'll get a notification. Sadly I don't have a time table, because of the current pandemic I can't really plan. You can be sure I will do it as quick as possible.

**Comment by ndelangen** [comment]
I wasn't meaning to rush you in any way. Really really appreciative of everything you do 👏

**Comment by vdjurdjevic** [comment]
@tooppaaa Do you have any idea how to implement textarea component? I managed to do that with similar approach, but instead of returning the whole dom structure (can't make it work), I just return textarea, and initialize plugin on the mount. The only problem is that there is blink of default text area until plugin does it's job. The only solution i have so far is to set visibility to hidden and reset it on mount. Any ideas?

**Comment by tooppaaa** [comment]
@KingSora any update on this one ?

**Comment by KingSora** [comment]
The newest version of `overlayscrollbars-react` is a complete rewrite and comes with a hook and component written with hooks.

Thank you very very much again for your contribution I really appreciate it.

**Pull request closed without merging**
